"""initial1

Revision ID: 5cfbf51f73bd
Revises: 055515579bb4
Create Date: 2025-01-22 01:17:58.155757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cfbf51f73bd'
down_revision: Union[str, None] = '055515579bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flares', sa.Column('exception_number', sa.String(), nullable=True))
    op.add_column('flares', sa.Column('submittal_date', sa.DateTime(), nullable=True))
    op.add_column('flares', sa.Column('filing_number', sa.String(), nullable=True))
    op.add_column('flares', sa.Column('status', sa.String(), nullable=True))
    op.add_column('flares', sa.Column('filing_type', sa.String(), nullable=True))
    op.add_column('flares', sa.Column('operator_number', sa.String(), nullable=True))
    op.add_column('flares', sa.Column('operator_name', sa.String(), nullable=True))
    op.add_column('flares', sa.Column('property', sa.String(), nullable=True))
    op.add_column('flares', sa.Column('effective_date', sa.DateTime(), nullable=True))
    op.add_column('flares', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    op.add_column('flares', sa.Column('fv_district', sa.String(), nullable=True))
    op.drop_column('flares', 'duration')
    op.drop_column('flares', 'date')
    op.drop_column('flares', 'volume')
    op.drop_column('flares', 'h2s')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flares', sa.Column('h2s', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flares', sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flares', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('flares', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('flares', 'fv_district')
    op.drop_column('flares', 'expiration_date')
    op.drop_column('flares', 'effective_date')
    op.drop_column('flares', 'property')
    op.drop_column('flares', 'operator_name')
    op.drop_column('flares', 'operator_number')
    op.drop_column('flares', 'filing_type')
    op.drop_column('flares', 'status')
    op.drop_column('flares', 'filing_number')
    op.drop_column('flares', 'submittal_date')
    op.drop_column('flares', 'exception_number')
    # ### end Alembic commands ###
