"""initialz1

Revision ID: b2284f80a514
Revises: 5cfbf51f73bd
Create Date: 2025-01-22 01:51:44.267527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2284f80a514'
down_revision: Union[str, None] = '5cfbf51f73bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flares', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('flares', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('flares', sa.Column('h2s', sa.Float(), nullable=True))
    op.add_column('flares', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flares', 'date')
    op.drop_column('flares', 'h2s')
    op.drop_column('flares', 'duration')
    op.drop_column('flares', 'volume')
    # ### end Alembic commands ###
